### ISSUE TITLE
Forget to spend money reminder

### ISSUE THREAD

**Issue by roasher** [MisterRnobe/sodexo-tg-bot#26]
Leroy Merlin fills our card up to N rubbles each month. If one forget to spend it there money will be lost.
User need to have an ability to enable a gently reminder, who will send few notifications

- in the middle of the month if sum is greater than N/2.
- (last working day of the month - 3 days) if sum is greater than 1000 rub.
- (last working day of the month - 1 days) if sum is greater than 500 rub.
- last working day of the month if sum is greater than 500 rub.

**Comment by MisterRnobe** [comment]
@roasher Hello there!
Thanks for your suggestion. It seems like a good and useful feature. 
Could you please provide a bit more information about how it may look like? Should this reminder be enabled via bot comands or a new menu item should be added? Which way N is set? Is it user specific variable or one value for all useres?
